ibm_cloud_fail_over/__init__.py,sha256=wbhBYFgjpXRsLHxkrubPZXlQQAtVu9Nj75lazY0A67c,275
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=UHi7yXVZUSscsHM2zcngbwkLsPzQtnUmeOfyHnv8gXg,25104
ibm_cloud_fail_over-1.0.11.dist-info/METADATA,sha256=1lnchyWtqIb7AVATH8FaohF4Giet7I0fPQkwz7TcCBI,7085
ibm_cloud_fail_over-1.0.11.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.11.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.11.dist-info/RECORD,,
