ibm_cloud_fail_over/__init__.py,sha256=wbhBYFgjpXRsLHxkrubPZXlQQAtVu9Nj75lazY0A67c,275
ibm_cloud_fail_over/ibm_cloud_fail_over.py,sha256=B_dvqqmb5ix474XfsM_YBerv--2phtLSYdr3eyOba3M,25097
ibm_cloud_fail_over-1.0.10.dist-info/METADATA,sha256=qXk43dRK8n4GTAsT-zI1pdb4-npOXUWHHsy_rh9a370,7085
ibm_cloud_fail_over-1.0.10.dist-info/WHEEL,sha256=qtCwoSJWgHk21S1Kb4ihdzI2rlJ1ZKaIurTj_ngOhyQ,87
ibm_cloud_fail_over-1.0.10.dist-info/licenses/LICENSE,sha256=xx0jnfkXJvxRnG63LTGOxlggYnIysveWIZ6H3PNdCrQ,11357
ibm_cloud_fail_over-1.0.10.dist-info/RECORD,,
